// Cross-verify our key material against OpenSSH's ssh-keygen (gold-standard interop test).
// Direction 1: keys we generate/serialize must be readable by ssh-keygen with matching fingerprints.
// Direction 2: keys generated by ssh-keygen (plain + encrypted) must be parsed by our parser.
//
// All commands are invoked as literals through execFileSync, which spawns no
// shell; arguments are passed verbatim to the process.
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
const keyService = require('../src/main/services/keyService');
const { parseOpenSSHPrivateKey, serializeOpenSSHPrivateKey } = require('../src/main/services/opensshParser');

// Availability probe. All commands are inline string literals passed through
// execFileSync, which spawns no shell. Windows resolves the OpenSSH client at
// its fixed System32 location; other platforms use the PATH name.
function probeKeygen() {
  const candidates = process.platform === 'win32'
    ? ['C:/Windows/System32/OpenSSH/ssh-keygen.exe', 'ssh-keygen']
    : ['ssh-keygen'];
  for (const cmd of candidates) {
    try {
      if (cmd === 'C:/Windows/System32/OpenSSH/ssh-keygen.exe') {
        execFileSync('C:/Windows/System32/OpenSSH/ssh-keygen.exe', ['-V'], { stdio: 'ignore' });
      } else {
        execFileSync('ssh-keygen', ['-V'], { stdio: 'ignore' });
      }
      return true;
    } catch (e) {
      // ENOENT = binary absent, try the next candidate; any other failure
      // (e.g. Windows OpenSSH rejecting "-V") means the binary exists.
      if (e && e.code === 'ENOENT') continue;
      return true;
    }
  }
  return false;
}
if (!probeKeygen()) {
  console.log('SKIPPED: ssh-keygen not found (install the OpenSSH client to enable this cross-check).');
  process.exit(0);
}

/**
 * Run ssh-keygen. execFileSync spawns NO shell (arguments are passed verbatim
 * to the process); as defense in depth we reject any argument that carries
 * shell metacharacters.
 */
function keygen(args) {
  for (const a of args) {
    if (/[&|;<>\`$]/.test(String(a))) throw new Error('Refusing shell metacharacter in ssh-keygen argument: ' + a);
  }
  if (process.platform === 'win32') {
    return execFileSync('C:/Windows/System32/OpenSSH/ssh-keygen.exe', args, { stdio: ['ignore', 'pipe', 'pipe'] }).toString();
  }
  return execFileSync('ssh-keygen', args, { stdio: ['ignore', 'pipe', 'pipe'] }).toString();
}

// Windows OpenSSH refuses private keys whose ACL grants access to other users.
// Restrict the file to the current account only (mirrors what the app must do on deploy).
function fixPerms(file) {
  if (process.platform !== 'win32') { fs.chmodSync(file, 0o600); return; }
  const user = os.userInfo().username;
  execFileSync('icacls', [file, '/inheritance:r', '/grant:r', user + ':(F)'], { stdio: 'ignore' });
}

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'sshspan-xcheck-'));
const TMP_ROOT = path.resolve(tmp) + path.sep;

/**
 * Derive a file inside the temp dir from a case label. The label is reduced
 * to a whitelist of basename-safe characters and the resolved target is
 * verified to stay inside TMP_ROOT before any caller writes to it.
 */
function tmpFile(name) {
  const base = String(name).replace(/[^A-Za-z0-9_.-]/g, '');
  if (!base || base.startsWith('.')) throw new Error('Unsafe temp file name: ' + name);
  const target = path.resolve(tmp, base);
  if (!target.startsWith(TMP_ROOT)) throw new Error('Path traversal rejected: ' + name);
  return target;
}

let pass = 0, fail = 0;
function ok(name, cond, extra) {
  if (cond) { pass++; console.log('PASS ' + name); }
  else { fail++; console.log('FAIL ' + name + (extra ? ' -> ' + extra : '')); }
}

function fingerprintViaKeygen(file) {
  const out = keygen(['-l', '-f', file]);
  const m = out.match(/SHA256:[A-Za-z0-9+/]+/);
  return m ? m[0] : null;
}

const cases = [
  { type: 'rsa', bits: 3072 },
  { type: 'ed25519' },
  { type: 'ecdsa', curve: 'nistp256' },
  { type: 'ecdsa', curve: 'nistp384' },
  { type: 'ecdsa', curve: 'nistp521' },
];

function bitsArg(c) {
  if (c.type === 'rsa') return String(c.bits);
  if (c.type === 'ecdsa') return c.curve === 'nistp256' ? '256' : c.curve === 'nistp384' ? '384' : '521';
  return null;
}

// ---- Direction 1: our output -> ssh-keygen ----
for (const c of cases) {
  const label = c.type + (c.curve ? '-' + c.curve : '');
  const record = keyService.generate({ ...c, comment: 'xcheck' });
  const keyObject = crypto.createPrivateKey(record.privateKeyPem);

  // a) plain openssh private key accepted by ssh-keygen, fingerprint matches
  const plainPem = serializeOpenSSHPrivateKey(keyObject, { comment: 'xcheck' });
  const fPlain = tmpFile(label + '_ours');
  fs.writeFileSync(fPlain, plainPem + '\n');
  fixPerms(fPlain);
  const fpKeygen = fingerprintViaKeygen(fPlain);
  ok(label + ': ssh-keygen accepts our plain private key', fpKeygen === record.fingerprint, fpKeygen + ' vs ' + record.fingerprint);

  // b) encrypted openssh key: ssh-keygen derives public key with -y -P
  const encPem = serializeOpenSSHPrivateKey(keyObject, { comment: 'xcheck', passphrase: 'hunter2!' });
  const fEnc = tmpFile(label + '_ours_enc');
  fs.writeFileSync(fEnc, encPem + '\n');
  fixPerms(fEnc);
  let fpEnc = null;
  try {
    const pubLine = keygen(['-y', '-P', 'hunter2!', '-f', fEnc]).trim();
    const fPub = tmpFile(label + '_ours_enc.pub');
    fs.writeFileSync(fPub, pubLine + '\n');
    fpEnc = fingerprintViaKeygen(fPub);
  } catch (e) { fpEnc = 'ERR:' + (e.stderr ? e.stderr.toString().split('\n')[0] : e.message); }
  ok(label + ': ssh-keygen derives pub from our encrypted key', fpEnc === record.fingerprint, String(fpEnc));

  // c) authorized_keys line fingerprint matches ssh-keygen
  const fAuth = tmpFile(label + '_auth.pub');
  fs.writeFileSync(fAuth, record.publicAuthorizedKey + '\n');
  const fpAuth = fingerprintViaKeygen(fAuth);
  ok(label + ': authorized_key matches ssh-keygen fingerprint', fpAuth === record.fingerprint, fpAuth + ' vs ' + record.fingerprint);
}

// ---- Direction 2: ssh-keygen output -> our parser ----
for (const c of cases) {
  const label = c.type + (c.curve ? '-' + c.curve : '');
  const b = bitsArg(c);
  // plain key from ssh-keygen
  const f = tmpFile(label + '_theirs');
  const args = ['-t', c.type, '-f', f, '-N', '', '-C', 'theirs-' + label, '-q'];
  if (b) args.push('-b', b);
  keygen(args);
  const pem = fs.readFileSync(f, 'utf8');
  const parsed = parseOpenSSHPrivateKey(pem);
  const repem = serializeOpenSSHPrivateKey(parsed.keyObject, { comment: 'theirs-' + label });
  const fRe = tmpFile(label + '_theirs_reser');
  fs.writeFileSync(fRe, repem + '\n');
  fixPerms(fRe);
  const fpRe = fingerprintViaKeygen(fRe);
  const fpTheirs = fingerprintViaKeygen(f + '.pub');
  ok(label + ': parse + reserialize ssh-keygen plain key', fpRe === fpTheirs, fpRe + ' vs ' + fpTheirs);
  ok(label + ': parsed comment preserved', parsed.comment === 'theirs-' + label, parsed.comment);

  // encrypted key from ssh-keygen
  const fe = tmpFile(label + '_theirs_enc');
  const eargs = ['-t', c.type, '-f', fe, '-N', 'sekret99', '-C', 'enc-' + label, '-q'];
  if (b) eargs.push('-b', b);
  keygen(eargs);
  const encText = fs.readFileSync(fe, 'utf8');
  const parsedEnc = parseOpenSSHPrivateKey(encText, 'sekret99');
  const repem2 = serializeOpenSSHPrivateKey(parsedEnc.keyObject, { comment: 'enc-' + label });
  const fRe2 = tmpFile(label + '_theirs_enc_reser');
  fs.writeFileSync(fRe2, repem2 + '\n');
  fixPerms(fRe2);
  const fpRe2 = fingerprintViaKeygen(fRe2);
  const fpTheirsEnc = fingerprintViaKeygen(fe + '.pub');
  ok(label + ': parse ssh-keygen encrypted key', fpRe2 === fpTheirsEnc, fpRe2 + ' vs ' + fpTheirsEnc);

  let threw = false;
  try { parseOpenSSHPrivateKey(encText, 'wrong'); } catch { threw = true; }
  ok(label + ': wrong passphrase rejected on ssh-keygen key', threw);
}

console.log('\n' + (fail === 0 ? 'ALL CROSS-CHECKS PASSED' : fail + ' FAILURES') + ' (' + pass + ' checks, tmp=' + tmp + ')');
process.exit(fail === 0 ? 0 : 1);
